spring:
  profiles:
    active:
    - dev

---
spring:
  profiles:  dev  #开发环境
  application:
    name: base-config-eccl-dev


---
spring:
  profiles:  test  #测试环境
  application:
    name:  base-config-eccl-test

#一定要是utf-8的格式