spring:
  profiles:
    active:
    - dev

---
server:
  prot: 8201
spring:
  profiles: dev
  application:
    name: base-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: base-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/


#一定要是utf-8的格式